src/main/java/com/flexrate/flexrate_back/FlexrateBackApplication.java, src/main/java/com/flexrate/flexrate_back/common/config/QuerydslConfig.java, src/main/java/com/flexrate/flexrate_back/common/dto/PaginationInfo.java, src/main/java/com/flexrate/flexrate_back/common/exception/ErrorCode.java, src/main/java/com/flexrate/flexrate_back/common/exception/FlexrateException.java, src/main/java/com/flexrate/flexrate_back/common/exception/GlobalExceptionHandler.java, src/main/java/com/flexrate/flexrate_back/member/api/MemberAdminController.java, src/main/java/com/flexrate/flexrate_back/member/application/AdminAuthChecker.java, src/main/java/com/flexrate/flexrate_back/member/application/AdminAuthCheckerImpl.java, src/main/java/com/flexrate/flexrate_back/member/application/MemberAdminService.java, src/main/java/com/flexrate/flexrate_back/member/domain/Member.java, src/main/java/com/flexrate/flexrate_back/member/domain/repository/MemberQueryRepository.java, src/main/java/com/flexrate/flexrate_back/member/domain/repository/MemberQueryRepositoryImpl.java, src/main/java/com/flexrate/flexrate_back/member/dto/MemberSearchRequest.java, src/main/java/com/flexrate/flexrate_back/member/dto/MemberSearchResponse.java, src/main/java/com/flexrate/flexrate_back/member/dto/MemberSummaryDto.java, src/main/java/com/flexrate/flexrate_back/member/enums/MemberStatus.java, src/main/java/com/flexrate/flexrate_back/member/enums/Sex.java, src/main/java/com/flexrate/flexrate_back/member/mapper/MemberMapper.java
#10
- DDD 구조에 따라 `application`, `domain`, `dto`, `mapper` 등 계층별로 분리
- QueryDSL 기반 동적 검색, 페이징, 정렬을 지원하도록 쿼리 레이어 구현
- @Valid + javax.validation 입력값 검증 Controller/Service에서 일관되게 처리
- 관리자 인증 `AdminAuthChecker` 인터페이스로 추상화
- 글로벌 예외 처리 추가 (notion API 명세서 문서 참고)
- MemberMapper를 통해 Entity → DTO 변환 책임 분리
- QueryDSL에서 동적 조건 조합 시, null-safe 처리와 enum 변환에서 컴파일 에러가 발생하여, Optional/삼항 연산자 및 enum 타입의 명확한 분리로 해결
- 페이징, 정렬 파라미터가 누락될 경우 기본값 적용 로직 추가
- 정상 응답
<hr/>
- 결과가 1개도 나오지 않을 경우
<hr/>
- 유효성 검증 미통과한 경우
<hr/>
- 관리자 권한이 필요할 경우
<hr/>
[postapi 문서 업데이트](https://documenter.getpostman.com/view/33657317/2sB2izEYwi#b6097471-5b0e-4af3-bd65-8f9411c241d1)
[API 명세서 확인](https://www.notion.so/ryuseunghan/API-1dec3966a143801f8e15e570b66006cc)
예제 코드 전달을 위해 테스트코드 없이 postman으로만 테스트 후 빠르게 PR합니다. 추후 테스트코드 추가 예정.
=> feat: 관리자용 사용자 목록 검색 API 구현

src/main/java/com/flexrate/flexrate_back/common/exception/ErrorCode.java, src/main/java/com/flexrate/flexrate_back/common/exception/GlobalExceptionHandler.java
- close #14
- **변경 이유**  
기존에는 ErrorCode와 HTTP 상태코드의 매핑이 분리되어 있어, 예외 처리 로직에서 불필요한 switch문이 필요했고, 새로운 에러 코드 추가 시 코드 일관성 및 유지보수가 어려웠습니다.
이를 개선하기 위해 ErrorCode에 HttpStatus 필드를 추가하여 각 에러 코드가 자신의 HTTP 상태코드를 스스로 가지도록 리팩토링했습니다.
- **변경 방식**  
ErrorCode enum에 HttpStatus 필드를 추가하고, 모든 에러 코드에 맞는 상태코드 지정
- **리뷰어 집중 포인트**
- 모든 ErrorCode에 HttpStatus가 올바르게 지정되어 있는지 확인 부탁드립니다.
- 기존의 예외 처리 흐름이 변경되었으므로, 실제 API 응답의 status, code, message가 모두 기대대로 동작하는지 확인이 필요합니다. 테스트는 했지만, 혹시라도 작업 도중 의도대로 동작되지 않는 경우 말씀해주세요.
- **문제점:**  
기존에 ErrorCode와 상태코드가 분리되어 있어,  
새로운 에러코드 추가 시마다 GlobalExceptionHandler의 switch문도 함께 수정해야 했고, 실수로 매핑이 어긋나는 문제가 발생할 수 있었습니다.
- **해결 방법:**  
ErrorCode에서 상태코드를 직접 관리하도록 구조를 변경함으로써 중복 코드를 제거하고, 매핑 실수를 방지할 수 있게 되었습니다.
- 에러 코드 정상 동작 확인 완료
=> chore: ErrorCode HttpStatus 추가

src/main/java/com/flexrate/flexrate_back/common/config/RestTemplateConfig.java, src/main/java/com/flexrate/flexrate_back/loan/api/LoanPreApplicationController.java, src/main/java/com/flexrate/flexrate_back/loan/application/LoanPreApplicationService.java, src/main/java/com/flexrate/flexrate_back/loan/dto/LoanPreApplicationRequest.java, src/main/java/com/flexrate/flexrate_back/loan/dto/LoanPreApplicationResponse.java, src/main/java/com/flexrate/flexrate_back/loan/enums/EducationStatus.java, src/main/java/com/flexrate/flexrate_back/loan/enums/EmploymentType.java, src/main/java/com/flexrate/flexrate_back/loan/enums/LoanPurpose.java, src/main/java/com/flexrate/flexrate_back/loan/enums/ResidenceType.java, src/test/java/com/flexrate/flexrate_back/loan/api/LoanPreApplicationControllerTest.java, src/test/java/com/flexrate/flexrate_back/loan/application/LoanPreApplicationServiceTest.java, src/test/java/com/flexrate/flexrate_back/loan/dto/LoanPreApplicationRequestTest.java
- close #12 
- 멤버 토큰 인증 및 예외 처리 관련한 코드는 제외된 상태입니다. (추후 추가 예정)
- 저번에 논의 나왔던 서비스에서 외부 심사 서버와의 요청 및 응답 dto까지 총 4개 작성해야하는 거 아닌가 하는 이야기가 나왔었는데 일단 dto 동일한 형태로 요청/응답이 오갈 것이라 생각하고 dto는 총 2개 작성했습니다.
- 외부 서버와의 http 통신을 위한 RestTemplate 설정 작업을 진행했습니다.
- Service에서 현재 외부 서버가 없다 보니 실제 응답을 해줄 수 없는 상황이라 테스트를 위해 주석으로 더미 데이터 반환 코드를 넣어두었습니다.
- dto, controller, service 총 3가지의 테스트 코드를 작성하였습니다.(이렇게 작성하는게 맞는지 궁금하네요.. 적극 리뷰 환영입니다.)
테스트코드 실행 화면
=> feature: 대출 신청 사전 정보 입력 API 구현

src/main/java/com/flexrate/flexrate_back/member/api/MemberAdminController.java, src/main/java/com/flexrate/flexrate_back/member/application/MemberAdminService.java, src/main/java/com/flexrate/flexrate_back/member/domain/Member.java, src/main/java/com/flexrate/flexrate_back/member/domain/repository/MemberRepository.java, src/main/java/com/flexrate/flexrate_back/member/dto/PatchMemberRequest.java, src/main/java/com/flexrate/flexrate_back/member/dto/PatchMemberResponse.java, src/test/java/com/flexrate/flexrate_back/member/application/MemberAdminServiceTest.java
- close #13 
- 특정 사용자 검색을 위해 MemberRepository 생성
- MemberAdminService와 Controller에 관련 코드 추가
- Member에 사용자 정보 수정을 위해서 @Setter 사용하는 대신 update 메서드 추가(QueryDSL 사용도 고려하였으나 프로젝트에 더 적절한 방식은 엔티티 update 메서드라고 생각했습니다.)
- service 테스트 코드까지 작성(나머지 테스트 코드는 추후에 추가하겠습니다.)
- postman 및 swagger로 테스트 해볼 때 서버 오류 발생. 사용자 데이터 넣는 걸 잊은 거였으므로 application.yml에서 ddl-auto: none->create 바꾸고 실행하여 데이터베이스에 table 생성. 이후 insert로 사용자 데이터를 생성하여 진행..^^
사용자(memberId=1) 값 수정
관리자 인증 실패
사용자가 존재하지 않음
필수 입력값 누락
=> feature: 관리자용 특정 사용자 정보 수정 API 구현

src/main/java/com/flexrate/flexrate_back/financialdata/domain/UserFinancialData.java, src/main/java/com/flexrate/flexrate_back/financialdata/enums/UserFinancialDataType.java, src/main/java/com/flexrate/flexrate_back/loan/api/LoanAdminController.java, src/main/java/com/flexrate/flexrate_back/loan/application/LoanAdminService.java, src/main/java/com/flexrate/flexrate_back/loan/application/repository/LoanTransactionQueryRepository.java, src/main/java/com/flexrate/flexrate_back/loan/application/repository/LoanTransactionQueryRepositoryImpl.java, src/main/java/com/flexrate/flexrate_back/loan/dto/TransactionHistoryResponse.java, src/main/java/com/flexrate/flexrate_back/loan/dto/TransactionHistorySummaryDto.java, src/main/java/com/flexrate/flexrate_back/loan/mapper/LoanTransactionMapper.java, src/test/java/com/flexrate/flexrate_back/loan/api/LoanAdminControllerTest.java
- close #20 
- 기존 오타 패키지명(finantial → financial)을 개선했으니, 기존 코드와의 호환성에 주의해 주세요.
- Querydsl 기반 QueryRepository 구현
- 거래 내역은 `occurredAt` 내림차순 정렬 기본 적용
- 추후 정렬 파라미터 확장 가능
- 응답 데이터 구조 및 예시
- 노션 참고: [API 명세서](https://www.notion.so/ryuseunghan/1e3c3966a143809990b3c5237591bfad)
- postman 문서화 갱신: [postman api 문서](https://documenter.getpostman.com/view/33657317/2sB2izEYwi)
- Spring Boot 3.3+에서 @MockBean 사용시 Deprecation 경고
→ JUnit5 + Mockito 조합으로 순수 단위 테스트 구조로 리팩토링
=> feat: 사용자 입금 내역 상세 조회 API 구현

build.gradle, src/main/java/com/flexrate/flexrate_back/FlexrateBackApplication.java, src/main/java/com/flexrate/flexrate_back/auth/RefreshTokenRepository.java, src/main/java/com/flexrate/flexrate_back/auth/api/TestTokenApiController.java, src/main/java/com/flexrate/flexrate_back/auth/api/TokenApiController.java, src/main/java/com/flexrate/flexrate_back/auth/application/RefreshTokenService.java, src/main/java/com/flexrate/flexrate_back/auth/application/TokenService.java, src/main/java/com/flexrate/flexrate_back/auth/domain/jwt/JwtAccessDeniedHandler.java, src/main/java/com/flexrate/flexrate_back/auth/domain/jwt/JwtAuthenticationEntryPoint.java, src/main/java/com/flexrate/flexrate_back/auth/domain/jwt/JwtProperties.java, src/main/java/com/flexrate/flexrate_back/auth/domain/jwt/JwtTokenProvider.java, src/main/java/com/flexrate/flexrate_back/auth/domain/jwt/RefreshToken.java, src/main/java/com/flexrate/flexrate_back/auth/domain/jwt/TokenAuthenticationFilter.java, src/main/java/com/flexrate/flexrate_back/auth/domain/repository/RefreshTokenRepository.java, src/main/java/com/flexrate/flexrate_back/auth/dto/CreateAccessTokenRequest.java, src/main/java/com/flexrate/flexrate_back/auth/dto/CreateAccessTokenResponse.java, src/main/java/com/flexrate/flexrate_back/common/config/SecurityConfig.java, src/main/java/com/flexrate/flexrate_back/common/config/SecurityConfigProperties.java, src/main/java/com/flexrate/flexrate_back/common/config/SwaggerConfig.java, src/main/java/com/flexrate/flexrate_back/common/exception/ErrorCode.java, src/main/java/com/flexrate/flexrate_back/common/exception/ErrorResponse.java, src/main/java/com/flexrate/flexrate_back/member/application/MemberService.java, src/main/java/com/flexrate/flexrate_back/member/domain/Member.java, src/main/java/com/flexrate/flexrate_back/member/domain/repository/MemberRepository.java, src/main/java/com/flexrate/flexrate_back/member/enums/Role.java, src/main/java/com/flexrate/flexrate_back/member/security/MemberDetails.java, src/main/resources/application.yml, src/test/java/com/flexrate/flexrate_back/jwt/JwtFactory.java, src/test/java/com/flexrate/flexrate_back/jwt/TokenApiControllerTest.java, src/test/java/com/flexrate/flexrate_back/jwt/TokenProviderTest.java
- close #22 
->TokenService, refreshTokenRepository, JwtProperties, JwtTokenProvider, RefreshToken, TokenAuthenticationFilter, RefreshTokenRepository, CreateAccessTokenRequest, CreateAccessTokenResponse, MemberDetails, JwtFactory 
-> TokenApiControllerTest, TokenProviderTest 
-> SwaggerConfig
-> JwtAccessDeniedHandler, JwtAuthenticationEntryPoint, SecurityConfig , SecurityConfigProperties, application.yml
->TokenApiController, TestTokenApiController  
-> ErrorCode 
-> Role
1. application.yml 시크릿 키 추가
```
jwt:
secretKey: ${JWT_SECRET_KEY}
```
2. 해당 값들을 변수로 접근하는 데 사용한 JwtProperties 클래스
```
@Getter
@Setter
@Component
@ConfigurationProperties(prefix = "jwt") // 자바 클래스에 프로퍼티 값을 가져와서 사용하는 annotation
public class JwtProperties {
private String secretKey;
}
```
3. 토큰을 생성하고 올바른 토큰인지 유효성 검사를 하고 …
=> chore: JWT 인증/인가 구현 및 Swagger, Spring Security 설정

src/main/java/com/flexrate/flexrate_back/common/exception/ErrorCode.java, src/main/java/com/flexrate/flexrate_back/common/exception/GlobalExceptionHandler.java, src/main/java/com/flexrate/flexrate_back/loan/api/LoanAdminController.java, src/main/java/com/flexrate/flexrate_back/loan/application/LoanAdminService.java, src/main/java/com/flexrate/flexrate_back/loan/application/repository/LoanApplicationRepository.java, src/main/java/com/flexrate/flexrate_back/loan/domain/LoanApplication.java, src/main/java/com/flexrate/flexrate_back/loan/dto/LoanApplicationStatusUpdateRequest.java, src/main/java/com/flexrate/flexrate_back/loan/dto/LoanApplicationStatusUpdateResponse.java, src/main/java/com/flexrate/flexrate_back/loan/enums/LoanApplicationStatus.java, src/main/java/com/flexrate/flexrate_back/member/domain/repository/MemberQueryRepositoryImpl.java, src/test/java/com/flexrate/flexrate_back/loan/application/LoanAdminServiceTest.java
- close #28
---
---
- 유효한 상태 전환만 허용하도록 유효성 체크 메서드를 엔티티에 추가했습니다. 불가능한 전환 시 LOAN_STATUS_CONFLICT 오류 코드가 반환됩니다.
- 가능한 상태 전환: PENDING -> REJECTED/EXECUTED, EXECUTED -> REJECTED/COMPLETED
- 리뷰 집중 포인트:
- 상태 전환 규칙이 충분한가?
- 예외 및 오류 코드가 명확하게 정의/처리되는가?
---
기존 예외 코드와 메시지가 혼재되어 있어 새로운 ErrorCode를 정의하고, 모든 예외 발생 지점에서 이를 사용하도록 리팩토링했습니다. (필수 파라미터 누락 에러 처리)
---
- L002 LOAN_NOT_FOUND
- L005 LOAN_STATUS_CONFLICT
- A000 AUTH_REQUIRED_FIELD_MISSING
- 200 OK
=> feat: 대출 상태 변경 API 구현

src/main/java/com/flexrate/flexrate_back/common/config/SecurityConfig.java, src/main/java/com/flexrate/flexrate_back/member/api/SignUpController.java, src/main/java/com/flexrate/flexrate_back/member/application/MemberService.java, src/main/java/com/flexrate/flexrate_back/member/domain/Member.java, src/main/java/com/flexrate/flexrate_back/member/domain/repository/MemberRepository.java, src/main/java/com/flexrate/flexrate_back/member/dto/SignupRequestDTO.java, src/main/java/com/flexrate/flexrate_back/member/dto/SignupResponseDTO.java, src/main/java/com/flexrate/flexrate_back/member/enums/Role.java, src/test/java/com/flexrate/flexrate_back/member/application/MemberServiceTest.java
- close #31 
- signupDTO의 값이 적절히 전달되고, 필드 예외 처리가 잘 동작하는가?
- Service 코드에 FlexrateException을 통해 처리되는 예외 코드랑 메시지가 잘 작성했는가?
- password 컬럼에 먼저 평문값을 입력 후 password_hash에 암호화 처리가 되어 MySQL DB에 저장
- Bcrypt로 처리되는 password_hash에 먼저 값을 넣어버려서 401코드 발생
- 명세서와 엔터티 필드 재확인 후 해결
- 프론트에서 보내는 JSON 필드명이 Java의 필드명과 다를 경우 매핑되지 않거나 Enum 값이 null 처리 문제
- 요청 DTO에 애노테이션으로 명시하여 프론트쪽에 JSON 필드와 매핑
MySQL
=> feat: 회원가입 등록 API 구현

src/main/java/com/flexrate/flexrate_back/auth/domain/jwt/JwtTokenProvider.java, src/main/java/com/flexrate/flexrate_back/loan/api/LoanAdminController.java, src/main/java/com/flexrate/flexrate_back/loan/application/LoanAdminService.java, src/main/java/com/flexrate/flexrate_back/member/api/MemberAdminController.java, src/main/java/com/flexrate/flexrate_back/member/application/AdminAuthChecker.java, src/main/java/com/flexrate/flexrate_back/member/application/AdminAuthCheckerImpl.java, src/main/java/com/flexrate/flexrate_back/member/application/MemberAdminService.java
- close #39 
- 관리자 검증 공통 메서드 `isAdmin`을 구현하였으니 검토해주시고, 앞으로 "관리자" 권한 검증이 필요할 경우, 해당 메서드를 사용해주시기 바랍니다.
```
public boolean isAdmin(String token) {
if (token == null || token.isEmpty()) return false;
// Bearer 접두어 제거
if (token.startsWith("Bearer ")) {
token = token.substring(7);
}
// 토큰 유효성 검사
if (!tokenProvider.validToken(token)) {
return false;
}
// Role 추출 및 검사
String role = tokenProvider.getRole(token);
return Role.ADMIN.name().equals(role);
}
```
- isAdmin 사용 방법
```
// A007 관리자 인증 체크
if (!adminAuthChecker.isAdmin(authHeader)) {
throw new FlexrateException(ErrorCode.ADMIN_AUTH_REQUIRED);
}
```
- ⭐ @HeoYeonGyu 제 로직 변경하면서 연규님 로직(관리자 API)까지 admin 메서드를 함께 통일하여 추가 및 개선하였으니, 확인 부탁드립니다!
- ⭐ @ryuseunghan role 기반 검증을 위해 JwtTokenProvider에 `getRole` 메서드를 추가하였으니 확인 부탁드립니다!
```
// 토큰 기반으로 유저 role 반환 …
```
=> fix: [공통] 관리자 권한 검증 로직 추가

src/main/java/com/flexrate/flexrate_back/common/config/SecurityConfig.java, src/main/java/com/flexrate/flexrate_back/common/exception/ErrorCode.java, src/main/java/com/flexrate/flexrate_back/member/api/MemberController.java, src/main/java/com/flexrate/flexrate_back/member/application/MemberService.java, src/main/java/com/flexrate/flexrate_back/member/domain/Member.java, src/main/java/com/flexrate/flexrate_back/member/dto/ConsumeGoalResponse.java, src/main/java/com/flexrate/flexrate_back/member/dto/MypageResponse.java, src/main/java/com/flexrate/flexrate_back/member/dto/MypageUpdateRequest.java, src/main/java/com/flexrate/flexrate_back/member/enums/ConsumeGoal.java
- close #53 
- 마이페이지 수정 API의 경우, 인자는 email 또는 소비 목표 두 가지이며 필수값이 아닙니다.
- 소비 타입별 목표 조회 API는 인증이 필요하지 않습니다. (SecurityConfig에 url 추가)
- 에러코드(ErrorCode) 추가되었습니다.
```
LOAN_CONSUMPTION_TYPE_MISMATCH("L011", "소비 유형이 일치하지 않습니다.", HttpStatus.BAD_REQUEST),
```
=> feature: 마이페이지 개인 정보 조회/수정 및 소비 타입별 목표 리스트 조회 API 구현

src/main/java/com/flexrate/flexrate_back/loan/api/LoanAdminController.java, src/main/java/com/flexrate/flexrate_back/loan/application/LoanAdminService.java, src/main/java/com/flexrate/flexrate_back/loan/application/repository/LoanAdminQueryRepository.java, src/main/java/com/flexrate/flexrate_back/loan/application/repository/LoanAdminQueryRepositoryImpl.java, src/main/java/com/flexrate/flexrate_back/loan/domain/LoanApplication.java, src/main/java/com/flexrate/flexrate_back/loan/dto/LoanAdminSearchRequest.java, src/main/java/com/flexrate/flexrate_back/loan/dto/LoanAdminSearchResponse.java, src/main/java/com/flexrate/flexrate_back/loan/dto/LoanAdminSearchSummaryDto.java, src/main/java/com/flexrate/flexrate_back/loan/enums/LoanType.java, src/main/java/com/flexrate/flexrate_back/loan/mapper/LoanApplicationMapper.java, src/main/java/com/flexrate/flexrate_back/member/api/MemberAdminController.java
- close #49 
- loanApplication을 가져다가 작업했습니다. 코드에 변경사항이 있습니다.
```
@Enumerated(EnumType.STRING)
@Column(nullable = false)
private LoanType loanType;
```
ENUM에 LoanType이 추가되었습니다.
- 명세서에 있던 LoanStatus의 경우 LoanApplicationStatus를 그대로 쓰면 될 것 같아 그대로 가져다 썼습니다. LoanType의 경우, 신규, 연장, 재가입이라고 되어있어 우선 넣긴 했는데... 그때 멘토님이 대출기간 연장을 말씀하셨던 것 같아 신규와 연장은 가져가는 게 맞는 것 같고, 재가입은… 아마 동일한 상품을 또 대출 받았을 때를 의미하는 게 아닌가 생각해서 이것도 그대로 가져가도 될 것 같다고 보는데 아닐 경우에는 LoanType ENUM 다시 수정하겠습니다.
- limitFrom과 limitTo의 경우 대출 가능 한도라고 되어있어서 처음에는 총 한도를 기준으로 하려고 했는데, 조회 시점에서 대출 가능한 한도를 기준으로 둔다면 totalAmount보다는 remainAmount가 적합하다고 생각하여 remainAmount로 바꾸었습니다.
- prevLoanCountFrom과 To의 경우에도 count를 기존 대출 횟수 최소라고 되어있는데 대출 횟수를 대출 거래(납입) 횟수라고 생각해서 transaction을 기준으로 count하게 하였습니다. 근데 생각해보니까 기존 대출 횟수면 한 member가 몇 개의 application을 가지고 있는지 따져야 하는 것 …
=> feature: 대출 현황 리스트 조회 API 구현

src/main/java/com/flexrate/flexrate_back/FlexrateBackApplication.java, src/main/java/com/flexrate/flexrate_back/common/converter/YearMonthAttributeConverter.java, src/main/java/com/flexrate/flexrate_back/common/exception/ErrorCode.java, src/main/java/com/flexrate/flexrate_back/financialdata/domain/UserFinancialData.java, src/main/java/com/flexrate/flexrate_back/financialdata/domain/repository/UserFinancialDataQueryRepository.java, src/main/java/com/flexrate/flexrate_back/financialdata/domain/repository/UserFinancialDataQueryRepositoryImpl.java, src/main/java/com/flexrate/flexrate_back/financialdata/domain/repository/UserFinancialDataRepository.java, src/main/java/com/flexrate/flexrate_back/financialdata/enums/UserFinancialCategory.java, src/main/java/com/flexrate/flexrate_back/report/api/ConsumptionHabitReportController.java, src/main/java/com/flexrate/flexrate_back/report/api/ReportStatisticsController.java, src/main/java/com/flexrate/flexrate_back/report/api/SchedulerTestController.java, src/main/java/com/flexrate/flexrate_back/report/application/ConsumptionHabitReportService.java, src/main/java/com/flexrate/flexrate_back/report/application/ConsumptionHabitReportServiceImpl.java, src/main/java/com/flexrate/flexrate_back/report/application/ReportStatisticsService.java, src/main/java/com/flexrate/flexrate_back/report/client/ConsumptionReportApiClient.java, src/main/java/com/flexrate/flexrate_back/report/domain/ConsumptionHabitReport.java, src/main/java/com/flexrate/flexrate_back/report/domain/repository/ConsumptionHabitReportRepository.java, src/main/java/com/flexrate/flexrate_back/report/dto/ConsumptionCategoryRatioResponse.java, src/main/java/com/flexrate/flexrate_back/report/dto/ConsumptionCategoryStatsResponse.java, src/main/java/com/flexrate/flexrate_back/report/dto/ConsumptionHabitReportResponse.java, src/main/java/com/flexrate/flexrate_back/report/scheduler/ConsumptionHabitReportScheduler.java
- close #52 
연월만 필요하기 때문에 YearMonth 타입으로 reportMonth를 선언하였습니다.
하지만 JPA에서는 YearMonth를 매핑하지 못하기 때문에 문자열로 변환시켜 저장할 수 있도록 하기 위해 다음과 같은 변환 코드를 만들었습니다.
```java
package com.flexrate.flexrate_back.common.converter;
import jakarta.persistence.AttributeConverter;
import jakarta.persistence.Converter;
import java.time.YearMonth;
import java.time.format.DateTimeFormatter;
@Converter(autoApply = false)
public class YearMonthAttributeConverter implements AttributeConverter<YearMonth, String> {
private static final DateTimeFormatter FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM");
@Override
public String convertToDatabaseColumn(YearMonth attribute) {
return attribute != null ? attribute.format(FORMATTER) : null;
}
@Override
public YearMonth convertToEntityAttribute(String dbData) {
return dbData != …
```
=> feature: 소비습관 리포트 조회 API 작업

src/main/java/com/flexrate/flexrate_back/member/application/MemberAdminService.java, src/main/java/com/flexrate/flexrate_back/member/dto/MemberDetailResponse.java
- close #63 
- startDate, endDate를 끌어다 대출 시작일과 대출 종료일을 return 했습니다.
- 납입일의 경우 기존의 YYYY-MM-DD 형식이 아니라 일자만 getDayOfMonth()로 분리하여 return 했습니다.
- 대출 원금은 대출 받을 때 결정된 대출 총액을 가져왔습니다.
- 총 상환 금액의 경우에는 지금까지 상환한 금액을 나타내는 건지, 아니면 대출 총액(대출 받은 원금)에 현재 조회된 이자율을 적용했을 때 예상되는 총 상환 금액을 보여주는 건지 모르겠어서 후자로 해두었습니다. 조회날짜의 이자율을 기준으로 구한 월 납입금에 전체 대출 기간(예: 12개월 상품이면 12만큼)을 곱해서 보여주는 방식으로 실제 총 상환 금액과는 분명한 차이가 있으리라고 생각합니다. 총 상환 금액을 보여주고자 하는 의도가 이자율이 변경됨에 따라 총 상환금액이 얼마나 줄어드는지 보여줌으로써 소비습관 개선을 장려하기 위함이라면 괜찮을 거라고 생각합니다.
하지만 총 상환 금액이 지금까지 상환한 금액을 나타내는 거라면 LoanApplication 엔티티에 총 상환 금액 필드를 만들고 월 납입일마다 납입금액을 상환할 때 총 상환 금액 또한 업데이트하는 식으로 LoanTransaction 쪽에서 로직을 생성해야 할 것 같습니다. 상세 조회에서는 해당 값을 단순히 조회하는 방식으로 가야합니다.
원리금균등분할상환의 경우 위와 같은 계산식을 이용합니다. 상세 조회에서도 월 납입금을 이러한 방식으로 산정하고 있습니다. 저희 상품은 매일 이자율이 달라지므로 납입금액 또한 납입일마다 달라져서 이미 저장된 총 …
=> fix: 관리자용 사용자 정보 상세 조회 API 로직 수정

src/main/java/com/flexrate/flexrate_back/member/domain/repository/MemberQueryRepositoryImpl.java, src/main/java/com/flexrate/flexrate_back/member/dto/MemberSearchRequest.java
- close #67
기존에는 생년월일과 거래내역 횟수에 대해 단일 값만 검색이 가능했으나, 요구사항에 따라 범위 검색이 필요해졌습니다. 이를 위해 DTO와 쿼리 모두 범위 조건을 지원하도록 리팩토링하였으며, 추후 확장성도 고려해 BooleanBuilder를 사용하였습니다.
(거래내역 수 필터링 시 member.loanApplication.loanTransactions.size()로 접근하는데, JPA 매핑 구조에 따라 N+1 문제가 발생할 여지가 있으니, 추후 실행 계획 분석을 통해 쿼리 튜닝 작업 여부를 판단할 예정입니다.)
=> fix: 고객 리스트 조회 API 개선

src/main/java/com/flexrate/flexrate_back/member/domain/repository/MemberQueryRepositoryImpl.java
- close #69 
기존에는 거래내역 횟수 조건 검색 시 대출 신청(loanApplication)이 없는 회원(거래내역 0건)이 결과에서 누락되는 문제가 있었습니다. 이는 member.loanApplication.isNotNull() 조건 때문이었고, 실제로 거래내역 0건 회원도 조건에 부합해야 하므로 쿼리 로직을 수정했습니다.
거래내역 횟수 조건에서 loanApplication이 없는 회원이 결과에서 누락되어 totalElements 값이 비정상적으로 감소하는 문제가 있었습니다.
이 문제를 해결하고자 QueryDSL의 CaseBuilder를 활용해 loanApplication이 null이면 거래내역 수를 0으로 처리, 모든 회원이 조건에 맞게 필터링되도록 쿼리를 수정하였습니다.
```java
builder.and(
new CaseBuilder()
.when(member.loanApplication.isNull())
.then(0)
.otherwise(member.loanApplication.loanTransactions.size())
.loe(request.transactionCountMax())
);
```
=> fIX: 고객 리스트 조회 쿼리 - 거래 횟수 범위 조건을 기반으로 올바른 결과를 반환하도록 쿼리 로직 개선

src/main/java/com/flexrate/flexrate_back/financialdata/enums/UserFinancialDataType.java, src/main/java/com/flexrate/flexrate_back/notification/enums/NotificationType.java, src/main/java/com/flexrate/flexrate_back/report/domain/ConsumptionHabitCategory.java, src/main/java/com/flexrate/flexrate_back/report/domain/ConsumptionHabitReport.java, src/main/resources/application-prod.yml, src/main/resources/application.yml, src/main/resources/db/migration/V1__init.sql, src/main/resources/db/migration/V999__init_dev_dummy_data.sql
- close #65 
- **application.yml, application-prod.yml ddl-auto를 `validate`로 변경**  
ddl-auto는 validate 또는 none으로 고정하고 사용하셔야 JPA가 임의로 테이블을 생성/수정하지 않고, Flyway 마이그레이션만을 통해 스키마 변경을 관리해줄 수 있습니다.
- 더미 데이터가 적절한지 확인해주시고, 추가 또는 개선하고싶은 데이터가있다면 말씀해주세요.
1) springboot는 "중지"상태에서, 도커 데이터베이스 콘솔에 진입해서 아래 명령어를 순서대로 입력
> mysql -u flexrate_user -p{flexrate DB 비밀번호}
> DROP DATABASE flexrate;
> CREATE DATABASE flexrate;
2) application.yml ddl-auto 확인
ddl-auto가 `none` 또는 `validate` 인지 확인.
- none: 아무런 작업도 하지 않음
- validate: 엔티티 클래스와 실제 DB 테이블의 구조가 일치하는지 검증
=> DDL 작업을 JPA가 아닌 flyway에게 위임하기 위함
3) springboot 재시작
4) 더미 데이터가 잘 들어가있는지 확인
`select * from member;`
등 아무 테이블이나 확인해서 데이터 들어와있으면 확인 완료
Flyway 마이그레이션(V1__init.sql)에서 외래키 참조 오류(`Failed to open the referenced table 'loan_transaction'`, MySQL 1824 에러)가 발생했습니다. …
=> chore: flyway 마이그레이션 파일 작성

src/main/java/com/flexrate/flexrate_back/loan/application/LoanService.java, src/main/java/com/flexrate/flexrate_back/loan/application/repository/LoanReviewHistoryRepository.java, src/main/java/com/flexrate/flexrate_back/loan/domain/LoanApplication.java, src/main/java/com/flexrate/flexrate_back/loan/domain/LoanReviewHistory.java, src/main/java/com/flexrate/flexrate_back/member/domain/MemberCreditSummary.java, src/main/java/com/flexrate/flexrate_back/report/domain/ConsumptionHabitCategory.java, src/main/resources/db/migration/V1__init.sql, src/main/resources/db/migration/V2__add_loan_review_history.sql, src/main/resources/db/migration/V999__init_dev_dummy_data.sql
- close #76 
- 회원 신용정보 산정 이력 엔티티(memberCreditSummary.java) 구현
- 대출 심사 이력 엔티티 구현 (LoanReviewHistory.java)
- 데이터베이스 스키마 변경 관리를 위한 Flyway 마이그레이션 스크립트 추가 (V2__add_loan_review_history.sql)
JPA 엔티티와 데이터베이스 테이블 간 외래 키 컬럼 이름 불일치로 인한 오류가 발생했습니다.
오류 메시지: `Schema-validation: missing column [report_report_id] in table [consumption_habit_category]`
이를 해결해주고자 `@JoinColumn(name = "report_id")`를 명시적으로 지정하여 실제 데이터베이스 컬럼 이름과 매핑을 일치시켰습니다.
=> feat: 회원 신용 정보 산정 이력 테이블 및 신용점수 산정 이력 테이블 추가 & 변경에 따른 flyway 버전관리

src/main/java/com/flexrate/flexrate_back/loan/application/LoanProductService.java, src/main/java/com/flexrate/flexrate_back/loan/application/repository/LoanTransactionRepository.java, src/main/java/com/flexrate/flexrate_back/loan/domain/LoanApplication.java, src/main/java/com/flexrate/flexrate_back/member/domain/Member.java
- close #77 
- 프론트와의 연동 시 selectProduct는 사용자가 특정 대출 상품을 선택했을 때 LoanApplication을 미리 생성하고, 기존 대출 신청이 존재할 경우에는 해당 신청의 status가 PRE_APPLIED일 때 삭제 후 생성해주어야 합니다. 기존 코드에서는 삭제가 불가하여 해당 문제 해결을 위해 코드를 수정하였습니다.
- 기존 코드에서는 삭제 시도 시 서버 내부 오류가 발생하면서 삭제가 제대로 이루어지지 않는 것을 확인했습니다.
- TransientObjectException 오류가 발생. LoanApplication 객체를 저장하려고 했지만, Hibernate 내부 flush 과정에서 아직 저장되지 않은 LoanApplication을 참조하는 다른 객체가 존재한다고 판단해 예외 발생한 것으로 loanApplicationRepository.delete(app); 후 flush()를 호출했을 때 문제가 생긴 걸 확인했습니다. 
- 연관된 자식 엔티티가 존재하는 상태에서 부모 삭제 시 문제가 발생하는데, LoanApplication에는 loanTransactions와 interests가 존재. 이 둘이 cascade 설정 없이 그대로 존재하고, 둘의 리스트가 초기화 되지 않아 LoanApplication 객체가 생성될 때 loanTransactions와 interests 리스트가 null인 것, 부모가 저장되기 전에 자식이 생성되며 참조하는 문제들이 있어서 삭제 시 TransientObjectException가 발생하였으므로 작업 내용에 기재한 것과 같이 해당 코드들을 …
=> fix: selectProduct API 수정 및 관련 파일 추가

src/main/java/com/flexrate/flexrate_back/member/api/MemberController.java, src/main/java/com/flexrate/flexrate_back/member/application/MemberService.java
=> feat: 사용자 대출 상태 조회 api 구현

src/main/java/com/flexrate/flexrate_back/common/exception/ErrorCode.java, src/main/java/com/flexrate/flexrate_back/report/application/ReportStatisticsService.java, src/main/java/com/flexrate/flexrate_back/report/domain/ConsumptionHabitReport.java
- close #98 
```
public ConsumptionCategoryStatsResponse getCategoryStats(Member member, YearMonth month) {
ConsumptionHabitReport report = reportRepository.findByMemberAndReportMonth(member, month)
.orElseThrow(() -> new FlexrateException(ErrorCode.REPORT_DOESNT_EXISTS));
List<ConsumptionCategoryRatioResponse> stats;
// consumptions가 비어 있거나 null이면 계산 및 json type으로 직렬화하여 저장
if (report.getConsumptions() == null || report.getConsumptions().isBlank()) {
stats = financialDataRepository.findCategoryStatsWithRatio(member, month);
try {
String consumptionsJson = objectMapper.writeValueAsString(stats);
report.setConsumptions(consumptionsJson);
reportRepository.save(report);
} catch (JsonProcessingException e) {
throw new FlexrateException(ErrorCode.JSON_SERIALIZATION_ERROR, e);
}
} else {
// …
```
=> fix : 특정 회원의 지정 월에 대한 카테고리별 소비 통계 조회 json type으로 저장하고, 재호출 시 저장된 데이터 반환

src/main/java/com/flexrate/flexrate_back/loan/application/LoanService.java, src/main/java/com/flexrate/flexrate_back/loan/domain/LoanReviewHistory.java
- close #119 
- `LoanService.java`
- `preApply` 메서드를 업데이트하여 대출 신청에 대한 `LoanReviewHistory`가 이미 존재하는지 확인하도록 변경. 
- 존재할 경우, 새로운 `updateReview` 메서드를 사용해 심사 세부 정보를 업데이트하고, 그렇지 않을 경우 이전과 동일하게 새로운 `LoanReviewHistory`를 생성
- `LoanReviewHistory.java`
- 기존 대출 심사 세부 정보를 업데이트할 수 있도록 새로운 `updateReview` 메서드 추가
```
// 대출 심사 결과 갱신
public void updateReview(EmploymentType employmentType, ResidenceType residenceType,
LoanPurpose loanPurpose, Integer annualIncome, Boolean isBankrupt) {
this.employmentType = employmentType;
this.residenceType = residenceType;
this.loanPurpose = loanPurpose;
this.annualIncome = annualIncome;
this.isBankrupt = isBankrupt;
}
```
=> fix: 대출 심사 결과 갱신 메서드 추가 및 대출 신청 사전 정보 저장 로직 수정

src/main/java/com/flexrate/flexrate_back/member/api/LoginController.java
- close #126 
- 기존 쿼리로 리프레쉬 토큰을 요청받았던 문제를 해결하기 위해 쿠키로 요청 받는 방식으로 수정합니다.
=> fix: 로그아웃 refreshToken 쿠키로 요청 받도록 수정

src/main/java/com/flexrate/flexrate_back/member/application/MemberAdminService.java
- close #141 
- 상세 조회에서 특정 멤버들의 페이지가 뜨지 않는 것을 확인했습니다. 주요 원인은 두 가지로 첫번째는 hasLoan이 true인 회원임에도 interest 더미데이터가 누락된 경우이고, 두번째는 hasLoan이 false여서 interest 값이 불필요한 회원들에 대해서도 상세 조회 로직에서 hasLoan 여부를 확인하기 전에 interest 조회를 먼저 수행하여 null 값으로 인한 오류가 발생한 경우입니다. 이를 해결하기 위해 더미데이터를 추가로 넣어주고 상세 조회 로직에서 interest 조회의 위치를 옮겼습니다.
두번째 경우에 해당하는 멤버의 페이지가 정상 조회됨을 확인
=> fix: 특정 고객의 상세 조회 불가 오류 수정

src/main/java/com/flexrate/flexrate_back/financialdata/application/UserFinancialDataService.java
- close #143 
- 랜덤값으로 인해 평가를 다시 받을 때마다 기존 점수와 비교했을 때 변동 폭이 너무 크므로 로직을 추가하여 해결했습니다.
기존 점수
재평가 시도 시
=> fix: 신용점수 산정 로직 수정
